# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
consumer_key: "IGCZTuqJIV06xWeoZ9dVRTzwx"
consumer_secret: "Oqll8z0qIgmTZgL0HY3ZtUGrZhgR5R4CikXaXQ999nq9ViaAdg"
access_token: "834852514394677250-PpRdwwDu8JTmbiodR7j4tc28uU1atxW"
access_token_secret:	"gjrC8wGcF2dbC49XQFLOMM7h6BdLDtckdOTcbE8ala4nU"
AWS_ACCESS_KEY: "AKIAJTTJFCIOQUVCTX7Q"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "bencekissfirst"
AWS_REGION: "us-east-2"
