# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
consumer_key: "lL23XKOu8HffHxPApcreRG3pw"
consumer_secret: "sG7CTdjeZivCVbcdbT68n2Unavb4MAyxM8ZzumI8989iyQ2kmC"
access_token: "836602813786517504-LyNXFXrHr8znTOmlad2cIWRM1txt6EC"
access_token_secret:	"sXbC7TQ43vqEG0GZnvxoiaURiXD8gESc0Sk9lpLip8NGE"
AWS_ACCESS_KEY: "AKIAI4I64ZBCZ26EYPWA"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "bencekissfirst"
AWS_REGION: "us-east-2"
