# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29dadd773837b1079e9c5e17467dec601596da33ffbd6ee5a699ebd04e0ebe679a98bc03cc0bb99941174b3686fe7d213e2115684e5731b78250fdd65d929cc5
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>

test:
  secret_key_base: 2fd863651f97483db799bcb55134340ca03c2fd41671bd6de54f8ed9923f7908d0105d0dd5b0812d63ff412e39103d13f72e9ea7e18e10fe1291556b8379fb32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
